# Generated by Django 5.1.6 on 2025-03-10 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="current_stack",
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="player",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="starting_stack",
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                ("current_round_number", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="core_game_is_acti_e738f7_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("question", models.CharField(max_length=150)),
                ("probability", models.FloatField()),
                ("multiplier", models.FloatField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Pending"), (1, "Active"), (2, "Completed")],
                        default=0,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("phase_duration", models.PositiveIntegerField(default=5)),
                (
                    "current_phase",
                    models.IntegerField(
                        choices=[
                            (0, "Initial Betting"),
                            (1, "Information"),
                            (2, "Final Betting"),
                            (3, "Results"),
                        ],
                        default=0,
                    ),
                ),
                ("result", models.BooleanField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="core.game",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Bet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bets",
                        to="core.player",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bets",
                        to="core.round",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="core_team_name_43878d_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players",
                to="core.team",
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["is_admin"], name="core_player_is_admi_364fc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["team"], name="core_player_team_id_62d5a9_idx"),
        ),
        migrations.AddIndex(
            model_name="round",
            index=models.Index(
                fields=["game", "number"], name="core_round_game_id_47f7b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="round",
            index=models.Index(fields=["status"], name="core_round_status_0b30ba_idx"),
        ),
        migrations.AddIndex(
            model_name="round",
            index=models.Index(
                fields=["game", "number", "status"],
                name="core_round_game_id_c66bce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="round",
            index=models.Index(
                fields=["game", "status"], name="core_round_game_id_b1479e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.UniqueConstraint(
                fields=("game", "number"), name="unique_round_number_per_game"
            ),
        ),
        migrations.AddIndex(
            model_name="bet",
            index=models.Index(fields=["round"], name="core_bet_round_i_28d6f7_idx"),
        ),
        migrations.AddIndex(
            model_name="bet",
            index=models.Index(fields=["player"], name="core_bet_player__4d5388_idx"),
        ),
        migrations.AddConstraint(
            model_name="bet",
            constraint=models.UniqueConstraint(
                fields=("player", "round"), name="unique_player_round_bet"
            ),
        ),
    ]
